{{- if .Values.flower.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secapi.fullname" . }}-flower
  labels:
    {{- include "secapi.flower.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "secapi.flower.labels" . | nindent 6 }}
      app.kubernetes.io/component: flower
  template:
    metadata:
      annotations:
        {{- with .Values.flower.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "secapi.flower.labels" . | nindent 8 }}
        app.kubernetes.io/component: flower
    spec:
      {{- include "secapi.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "secapi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.flower.podSecurityContext | nindent 8 }}
      containers:
        - name: flower
          securityContext:
            {{- toYaml .Values.flower.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5555
              protocol: TCP
          command:
            - celery
            - -A
            - app.core.celery
            - flower
            - --port=5555
            {{- if .Values.flower.basicAuth.enabled }}
            - --basic_auth={{ .Values.flower.basicAuth.username }}:{{ .Values.flower.basicAuth.password }}
            {{- end }}
          env:
            {{- if .Values.existingSecret }}
            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: celery-broker-url
            - name: CELERY_RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: celery-result-backend
            {{- else }}
            - name: CELERY_BROKER_URL
              value: {{ include "secapi.celeryBrokerUrl" . }}
            - name: CELERY_RESULT_BACKEND
              value: {{ include "secapi.celeryResultBackend" . }}
            {{- end }}
            {{- with .Values.global.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.flower.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.flower.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.flower.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.flower.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
