{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "secapi.fullname" . }}-api
  namespace: {{ include "secapi.namespace" . }}
  labels:
    {{- include "secapi.api.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "secapi.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}
