apiVersion: v2
name: secapi
description: SecAPI - Open-source security scanning API platform wrapping Trivy, Checkov, and TruffleHog
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - security
  - scanning
  - trivy
  - checkov
  - trufflehog
  - api
maintainers:
  - name: Fazal
    url: https://github.com/fazalfarhan
home: https://github.com/fazalfarhan/secapi
sources:
  - https://github.com/fazalfarhan/secapi
icon: https://raw.githubusercontent.com/fazalfarhan/secapi/main/docs/logo.png
annotations:
  artifacthub.io/category: security
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Documentation
      url: https://github.com/fazalfarhan/secapi#readme
